### ISSUE TITLE
Track page generation time

### ISSUE THREAD

**Issue by tsteur** [piwik/plugin-AnonymousPiwikUsageMeasurement#1]
We should track page generation time, also time that it takes to load a page via XHR in Dashboard area.

Ideally we would separate between loading time of XHR and loading time of page (with parsing, rendering etc) but think Piwik cannot handle this yet.

**Comment by mattab** [comment]
:+1: for a great user experience we need speed. Measuring speed of Piwik as felt by users, would be very valuable, to help us build an awesome product and experience!
