### ISSUE TITLE
Setup Travis CI build for AnonymousPiwikUsageMeasurement

### ISSUE THREAD

**Issue by mattab** [piwik/plugin-AnonymousPiwikUsageMeasurement#10]
I think we should setup the travis CI build for this repo. It will help us detect whether tests are failing, before we update submodules on piwik/piwik

eg. this submodule update broke the piwik platform build: https://travis-ci.org/piwik/piwik/jobs/85784574

```
....................PHP Fatal error:  Cannot use Piwik\Db\Settings as Settings because the name is already in use in /home/travis/build/piwik/piwik/plugins/AnonymousPiwikUsageMeasurement/Updates/0.1.1.php on line 13

Fatal error: Cannot use Piwik\Db\Settings as Settings because the name is already in use in /home/travis/build/piwik/piwik/plugins/AnonymousPiwikUsageMeasurement/Updates/0.1.1.php on line 13


```

**Comment by tsteur** [comment]
We can add it but don't think it's important. Personally I never have a look there anyway since it takes too long to get a result. Even when it takes only 2 minutes to run tests it is too long as one kinda has to wait for it unless one switches between tasks all the time etc.

**Comment by tsteur** [comment]
I'm reopening it as I don't get the system tests to work. It looks like there are no artifacts uploaded for plugins so I have not really a clue why it doesn't work. They run locally without any issues.

@diosmosis do you mind having a quick look at https://travis-ci.org/piwik/plugin-AnonymousPiwikUsageMeasurement/jobs/86173591 ? Maybe you have an idea?

**Comment by diosmosis** [comment]
I can reproduce locally either, looks like some travis environment issue. Would have to debug travis to figure out exactly what's happening, though it looks like there's something wrong happening during fixture setup.

**Comment by tsteur** [comment]
I'm investigating...

**Comment by tsteur** [comment]
So far I found out the fixture is actually setup correctly. It records all API calls, and it tracks all API calls (`{"status":"success","tracked":15,"invalid":0}`). It looks like the report invalidation is maybe not working... i continue to debug

**Comment by tsteur** [comment]
It works. Updating the minimum required version from `b17` to `rc1` fixed it. Guess there was a bug in Piwik
