### ISSUE TITLE
Failure when downloading AnonymousPiwikUsageMeasurement from marketplace

### ISSUE THREAD

**Issue by mattab** [piwik/plugin-AnonymousPiwikUsageMeasurement#12]
refs https://github.com/piwik/piwik/issues/9051

Fatal error</b>:  Call to a member function getValue() on null in <b>/home/piwik-demo/www/demo.piwik.org/core/Settings/Setting.php</b> on line <b>244</b><br />

**Comment by mattab** [comment]
It fails on this line: https://github.com/piwik/plugin-AnonymousPiwikUsageMeasurement/blob/0.1.1/AnonymousPiwikUsageMeasurement.php#L115

Not sure how to fix this issue?

**Comment by tsteur** [comment]
This is not related to the Marketplace but to not allowing users to opt out
