### ISSUE TITLE
Issue tracking request over HTTPS when Piwik is used over SSL

### ISSUE THREAD

**Issue by mattab** [piwik/plugin-AnonymousPiwikUsageMeasurement#13]
When Piwik server usage is tracked by this plugin, the JS tracking code should issue request over `https://` whenever this Piwik is used over SSL.

Currently, it loads over HTTP and browser displays a warning:

![warning](https://cloud.githubusercontent.com/assets/466765/10596199/110c5384-773e-11e5-8933-125d9b4bfa6d.png)

**Comment by tsteur** [comment]
Did you specify https in the URL?

**Comment by mattab** [comment]
I think I did specify https but not sure.

independently of the scheme used, it should be rewritten to match the current page scheme, ie. forced to https on HTTPS and left "as is found in settings" on http pages

**Comment by tsteur** [comment]
OK I'll add it as it seems we do same with tracking code generator. I'll also add a note to readme about HTTPS being required under circumstances
