### ISSUE TITLE
Make a setting to track logins/aliases as UserID

### ISSUE THREAD

**Issue by mgonera** [piwik/plugin-AnonymousPiwikUsageMeasurement#25]
For some users it would be useful to be able to view visitor profiles openly, that is, to be able to tell who is who. For this we should make an option to track Piwik login as UserID. Of course such information shall not be sent to Piwik founders if someone is sending anonymous information out. It should work only for tracking with your own Piwik.

**Comment by mattab** [comment]
we shouldn't do it by default (because plugin is called `Anonymous`) but it would make lots of sense to add a new setting (actually too), something like `Track the Piwik username as User ID` below `Send anonymize usage data to a custom Piwik` and below `Send anonymize usage data to this Piwik`

**Comment by mgonera** [comment]
@mattab also, we should add an option to send un-anonymized data to your own Piwik, and anonymize it only when sending it to Piwik team. This would actually make this feature useful for customers checking out usage of their coworkers, to establish whether or not they need more training for example.

**Comment by mattab** [comment]
Fixed in https://github.com/piwik/plugin-AnonymousPiwikUsageMeasurement/issues/27 - Kuddos @andrzejewsky
