### ISSUE TITLE
Data tracked on own server shows wrong URL

### ISSUE THREAD

**Issue by RMastop** [piwik/plugin-AnonymousPiwikUsageMeasurement#26]
When I send data to an ID on the same Server, It still shows the demo-anonymous.piwik.org URL, instead of the URL of the server.

I expected this to have the actual URL.

**Comment by tsteur** [comment]
This is currently on purpose to make sure to not leak any data and to make sure the URL is anonmyized but we could make it configurable.

**Comment by mattab** [comment]
Thanks for the report!

This was fixed in https://github.com/piwik/plugin-AnonymousPiwikUsageMeasurement/issues/25

Now you can un-check "Anonymise tracking requests" so that the correct URLs will be stored.
